### ISSUE TITLE
时装箱子翻译反了

### ISSUE THREAD

**Issue by NEOLEE98** [BDO-CnHope/bdocn#3]
简体中文 Premium显示为经典，Classic显示为精品

**Comment by Naunter** [comment]
这个翻译确实是有问题……但台服的官方文本就是这么写的……

![image](https://user-images.githubusercontent.com/17890335/122924944-50a9d680-d334-11eb-94a2-e0365338356e.png)
![image](https://user-images.githubusercontent.com/17890335/122925064-7931d080-d334-11eb-8634-96b8278b3c63.png)

这个只能看官方会不会更正了……毕竟我这个翻译的文本用的是台服的

**Comment by Naunter** [comment]
emmmm， 文本量有点大，我找个时间再修(咕
