### ISSUE TITLE
我想问问languagedata_cn.loc的制作方法

### ISSUE THREAD

**Issue by ghost** [BDO-CnHope/bdocn#4]
我想问问languagedata_cn.loc的制作方法

**Comment by ghost** [comment]
可以加个联系方式吗

**Comment by Naunter** [comment]
> 我想问问languagedata_cn.loc的制作方法

因为防止服务端被滥用，而且里面包含了一些闭源的代码，所以没有公开的打算。

#### 服务端的大致的工作流程:

1. 获取美服的.loc文件 ---> 解压美服的.loc文件 ---> 将解压的.loc文件输出为可编辑文本文件 ---> 对文本进行翻译 (弃坑后没再维护，已经停用了) 

2. 获取台服的.loc文件 ---> 解压台服的.loc文件 ---> 将解压的.loc文件输出为可编辑文本文件 

3. 将从第1步和第2步里获得的美服和台服的文本合并，这里称为"合并文本-繁体"

4. 将"合并文本-繁体"转换为"合并文本-简体"
 
5. 将"合并文本-简体"重新打包为.loc文件

6. 上传重新打包的.loc文件

7. 因为是一个自动程序，所以每周会自己检查新版合并更新上传。

**Comment by Naunter** [comment]
> 可以加个联系方式吗

不好意思，暂时没有公开联系方式的打算。但如果你有问题，可以在Github里提出，或者在B站上联系我，我会不定期的上去查看并回复的。

**Comment by Naunter** [comment]
这个汉化工具项目已经暂停更新和维护了。感谢你的使用和支持。
