### ISSUE TITLE
活动物品、价值产包全部为韩文

### ISSUE THREAD

**Issue by itinybad** [BDO-CnHope/bdocn#5]
steam服，使用繁体中文，汉化器配置如下
![image](https://github.com/BDO-CnHope/bdocn/assets/13375605/24b79468-1257-4042-9e00-771c6fa6997e)

![QQ截图20231111124730](https://github.com/BDO-CnHope/bdocn/assets/13375605/2083b04d-61b5-4ade-b900-e7b8bc167430)
![QQ截图20231111124710](https://github.com/BDO-CnHope/bdocn/assets/13375605/7bf3dc91-4e41-4c47-88c6-bb90996c14df)
![QQ截图20231111124719](https://github.com/BDO-CnHope/bdocn/assets/13375605/b103662b-d02c-4d13-aec5-ab8583ec2e79)

**Comment by Naunter** [comment]
商城里的条目出现韩文或者乱码是因为这个汉化包没有对商城里的条目进行汉化。

而且不好意思啊，这个汉化工具项目已经暂停更新和维护了。如需要更好的体验，请在网上另寻其它的汉化工具使用吧。

感谢你的使用和支持。
